repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.7
    hooks:
    - id: clang-format
      types_or: [c++, c]
      files: 'libtiledbvcf/.*|apis/java/src/main/java/io/tiledb/libvcfnative/.*|apis/python/src/.*'
      exclude: 'libtiledbvcf/external/.*'
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
    - id: ruff-check
      types_or: [ python, pyi ]
      args: ["--config=apis/python/pyproject.toml"]
    - id: ruff-format
      types_or: [ python, pyi ]
      args: ["--config=apis/python/pyproject.toml"]
