repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.7
    hooks:
    - id: clang-format
      types_or: [c++, c]
      files: 'libtiledbvcf/.*|apis/java/src/main/java/io/tiledb/libvcfnative/.*|apis/python/src/.*'
      exclude: 'libtiledbvcf/external/.*'
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
    - id: black
      files: 'apis/python/src/.*'
