# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/dudoslav/.miniforge3/bin/cmake

# The command to remove a file.
RM = /home/dudoslav/.miniforge3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dudoslav/Projects/TileDB-VCF/libtiledbvcf

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dudoslav/Projects/TileDB-VCF

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/home/dudoslav/.miniforge3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/dudoslav/.miniforge3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dudoslav/Projects/TileDB-VCF/CMakeFiles /home/dudoslav/Projects/TileDB-VCF//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dudoslav/Projects/TileDB-VCF/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ep_cli11

# Build rule for target.
ep_cli11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ep_cli11
.PHONY : ep_cli11

# fast build rule for target.
ep_cli11/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ep_cli11.dir/build.make CMakeFiles/ep_cli11.dir/build
.PHONY : ep_cli11/fast

#=============================================================================
# Target rules for targets named ep_htslib

# Build rule for target.
ep_htslib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ep_htslib
.PHONY : ep_htslib

# fast build rule for target.
ep_htslib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ep_htslib.dir/build.make CMakeFiles/ep_htslib.dir/build
.PHONY : ep_htslib/fast

#=============================================================================
# Target rules for targets named ep_spdlog

# Build rule for target.
ep_spdlog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ep_spdlog
.PHONY : ep_spdlog

# fast build rule for target.
ep_spdlog/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ep_spdlog.dir/build.make CMakeFiles/ep_spdlog.dir/build
.PHONY : ep_spdlog/fast

#=============================================================================
# Target rules for targets named ep_tiledb

# Build rule for target.
ep_tiledb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ep_tiledb
.PHONY : ep_tiledb

# fast build rule for target.
ep_tiledb/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ep_tiledb.dir/build.make CMakeFiles/ep_tiledb.dir/build
.PHONY : ep_tiledb/fast

#=============================================================================
# Target rules for targets named ep_catch

# Build rule for target.
ep_catch: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ep_catch
.PHONY : ep_catch

# fast build rule for target.
ep_catch/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ep_catch.dir/build.make CMakeFiles/ep_catch.dir/build
.PHONY : ep_catch/fast

#=============================================================================
# Target rules for targets named format

# Build rule for target.
format: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 format
.PHONY : format

# fast build rule for target.
format/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/format.dir/build.make CMakeFiles/format.dir/build
.PHONY : format/fast

#=============================================================================
# Target rules for targets named check-format

# Build rule for target.
check-format: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check-format
.PHONY : check-format

# fast build rule for target.
check-format/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check-format.dir/build.make CMakeFiles/check-format.dir/build
.PHONY : check-format/fast

#=============================================================================
# Target rules for targets named libtiledbvcf

# Build rule for target.
libtiledbvcf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libtiledbvcf
.PHONY : libtiledbvcf

# fast build rule for target.
libtiledbvcf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libtiledbvcf.dir/build.make CMakeFiles/libtiledbvcf.dir/build
.PHONY : libtiledbvcf/fast

#=============================================================================
# Target rules for targets named install-libtiledbvcf

# Build rule for target.
install-libtiledbvcf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 install-libtiledbvcf
.PHONY : install-libtiledbvcf

# fast build rule for target.
install-libtiledbvcf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/install-libtiledbvcf.dir/build.make CMakeFiles/install-libtiledbvcf.dir/build
.PHONY : install-libtiledbvcf/fast

#=============================================================================
# Target rules for targets named skbuild-export

# Build rule for target.
skbuild-export: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 skbuild-export
.PHONY : skbuild-export

# fast build rule for target.
skbuild-export/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skbuild-export.dir/build.make CMakeFiles/skbuild-export.dir/build
.PHONY : skbuild-export/fast

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check.dir/build.make CMakeFiles/check.dir/build
.PHONY : check/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... check"
	@echo "... check-format"
	@echo "... ep_catch"
	@echo "... ep_cli11"
	@echo "... ep_htslib"
	@echo "... ep_spdlog"
	@echo "... ep_tiledb"
	@echo "... format"
	@echo "... install-libtiledbvcf"
	@echo "... libtiledbvcf"
	@echo "... skbuild-export"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

