FROM amazonlinux:latest

ENV AWS_EC2_METADATA_DISABLED true

# Install some dependencies
RUN yum -y install which wget git tar gzip unzip gcc-c++ zlib-devel \
       openssl-devel bzip2-devel tbb-devel libcurl-devel xz-devel make \
       automake autoconf \
    && yum clean all

# Install a newer version of CMake (TileDB requires >= 3.3)
RUN wget https://cmake.org/files/v3.12/cmake-3.12.3-Linux-x86_64.sh \
    && sh cmake-3.12.3-Linux-x86_64.sh --skip-license --prefix=/usr/ \
    && rm cmake-3.12.3-Linux-x86_64.sh

# Copy the TileDB-VCF directory and build it.
WORKDIR /tmp
COPY libtiledbvcf libtiledbvcf

WORKDIR /tmp/libtiledbvcf/build
RUN cmake .. -DCMAKE_BUILD_TYPE=Release \
             -DCMAKE_INSTALL_PREFIX=/usr/local \
             -DOVERRIDE_INSTALL_PREFIX=OFF \
    && make -j4 \
    && make install-libtiledbvcf
RUN rm -rf /tmp/libtiledbvcf

WORKDIR /data
ENTRYPOINT ["/usr/local/bin/tiledbvcf"]
