#
# Dockerfile-cli
#
#
# The MIT License
#
# Copyright (c) 2018 TileDB, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
# This Dockerfile builds the TileDB-VCF CLI image.
#

FROM amazonlinux:latest

# Install some dependencies
RUN yum -y install which wget git tar gzip unzip gcc-c++ zlib-devel \
       openssl-devel bzip2-devel tbb-devel libcurl-devel xz-devel make \
       automake autoconf \
    && yum clean all

# Install a newer version of CMake (TileDB requires >= 3.3)
RUN wget https://cmake.org/files/v3.12/cmake-3.12.3-Linux-x86_64.sh \
    && sh cmake-3.12.3-Linux-x86_64.sh --skip-license --prefix=/usr/ \
    && rm cmake-3.12.3-Linux-x86_64.sh

# Copy the TileDB-VCF directory and build it.
WORKDIR /tmp
COPY libtiledbvcf libtiledbvcf

WORKDIR /tmp/libtiledbvcf/build
RUN cmake .. -DCMAKE_BUILD_TYPE=Release \
             -DCMAKE_INSTALL_PREFIX=/usr/local \
             -DOVERRIDE_INSTALL_PREFIX=OFF \
    && make -j4 \
    && make install-libtiledbvcf

WORKDIR /tmp
RUN rm -rf /tmp/libtiledbvcf

ENTRYPOINT ["/usr/local/bin/tiledbvcf"]
