FROM daskdev/dask:latest

RUN conda config --prepend channels conda-forge

# Install some dependencies
RUN apt-get update \
    && apt-get install --no-install-recommends -y \
         wget cmake git gcc g++ build-essential autoconf automake \
         libssl-dev libbz2-dev liblz4-dev libcurl4-openssl-dev \
         zlib1g-dev liblzma-dev \
         python3 python3-dev python3-venv \
    && rm -rf /var/lib/apt/lists/*

# Copy the TileDB-VCF Python directory and build it.
WORKDIR /tmp/
COPY . tiledbvcf
RUN cd tiledbvcf \
    && rm -rf libtiledbvcf/build dist \
    && cd apis/python \
    && conda env update -n base -f conda-env.yml \
    && python setup.py install \
    && cd /tmp \
    && rm -rf tiledbvcf \
    && conda clean -a -y
