FROM ubuntu:20.04

ENV AWS_EC2_METADATA_DISABLED true
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

# Install some dependencies
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    cmake \
    wget \
    git \
    tar \
    gzip \
    unzip \
    libz-dev \
    libssl-dev \
    libbz2-dev \
    libcurl4-openssl-dev \
    xz-utils \
    liblzma-dev \
    make \
    automake \
    autoconf \
    patch \
    build-essential \
    python3 \
    python3-dev \
    python3-pip \
    python-is-python3 \
    && apt-get clean \
    && apt-get purge -y \
    && rm -rf /var/lib/apt/lists*

# avoid --home to prevent issues with singularity
RUN pip install --no-cache-dir \
    pandas \
    pyarrow \
    setuptools_scm \
    tiledb

# Build TileDB-VCF
WORKDIR /tmp
COPY . TileDB-VCF

WORKDIR /tmp/TileDB-VCF/apis/python

RUN python setup.py install

RUN rm -r /tmp/TileDB-VCF

WORKDIR /data
ENTRYPOINT ["python3"]
