FROM amazonlinux:latest as builder

ENV AWS_EC2_METADATA_DISABLED true

# Install some dependencies
RUN yum -y install cmake3 which wget git tar gzip unzip gcc-c++ zlib-devel \
       openssl-devel bzip2-devel libcurl-devel xz-devel make \
       automake autoconf \
    && yum clean all

WORKDIR /tmp
COPY libtiledbvcf libtiledbvcf
# Needed to properly detect TileDB-VCF version
COPY .git .git

WORKDIR /tmp/libtiledbvcf/build
RUN cmake3 .. -DCMAKE_BUILD_TYPE=Release \
             -DCMAKE_INSTALL_PREFIX=/usr/local \
             -DOVERRIDE_INSTALL_PREFIX=OFF \
    && make -j4 \
    && make install-libtiledbvcf

FROM amazonlinux:latest
COPY --from=builder /usr/local/bin/* /usr/local/bin/
COPY --from=builder /usr/local/include/* /usr/local/include/
COPY --from=builder /usr/local/lib/* /usr/local/lib/

WORKDIR /data
ENTRYPOINT ["/usr/local/bin/tiledbvcf"]
