#
# Dockerfile-py
#
#
# The MIT License
#
# Copyright (c) 2018 TileDB, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
# This Dockerfile builds the TileDB-VCF Python image.
#

FROM continuumio/miniconda3:4.8.2
ENV CFLAGS "-march=haswell"
ENV CPPFLAGS "-march=haswell"

ENV TILEDBVCF_FORCE_EXTERNAL_HTSLIB=OFF
ENV LD_LIBRARY_PATH=/usr/local/lib:/opt/conda/lib

RUN conda config --prepend channels conda-forge

# Install some dependencies
RUN apt-get update \
    && apt-get install --no-install-recommends -y \
       build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy the TileDB-VCF Python directory and build it.
WORKDIR /tmp
COPY . tiledbvcf


RUN cd tiledbvcf \
    && rm -rf libtiledbvcf/build dist \
    && cd apis/python \
    && conda env update -n base -f conda-env.yml \
    && conda install -y -c bioconda htslib \
    && conda install -y cmake \
    && conda clean -a -y

RUN cd /tmp/tiledbvcf/apis/python \
    && python setup.py install

RUN cd /tmp && rm -rf tiledbvcf

ENTRYPOINT ["/bin/bash"]
