FROM continuumio/miniconda3:4.10.3
ENV CFLAGS "-march=haswell"
ENV CPPFLAGS "-march=haswell"

ENV AWS_EC2_METADATA_DISABLED true
ENV TILEDBVCF_FORCE_EXTERNAL_HTSLIB=OFF
ENV LD_LIBRARY_PATH=/usr/local/lib:/opt/conda/lib

# Install some dependencies
RUN apt-get update \
    && apt-get install --no-install-recommends -y \
       build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy the TileDB-VCF Python directory and build it.
COPY apis/python/conda-env.yml .
RUN conda env update -n base -f conda-env.yml \
    && conda install -y -c bioconda 'htslib>=1.8' \
    && conda install -y 'cmake>=3' \
    && conda clean -a -y \
    && rm conda-env.yml

WORKDIR /tmp
COPY . tiledbvcf

WORKDIR /tmp/tiledbvcf/apis/python
RUN python setup.py install
RUN rm -rf /tmp/tiledbvcf

WORKDIR /data
ENTRYPOINT ["python3"]
