name: py4vcf
channels:
  - conda-forge
  - nodefaults
dependencies:
  # build
  - numpy
  - pandas
  - pyarrow=9
  - pybind11
  - python=3.9
  - setuptools
  - setuptools_scm
  - setuptools_scm_git_archive
  - wheel
  # test
  - dask
  - fsspec<2023.3.0
  - pytest
  - tiledb-py
