# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vcf_read <- function(uri, attributes, regions, samples) {
    .Call(`_tiledbvcf_vcf_read`, uri, attributes, regions, samples)
}

vcf_version <- function() {
    .Call(`_tiledbvcf_vcf_version`)
}

