name: tiledbvcf-py
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - pybind11>=2.10.0
  - pyarrow>=9.0.0
  - fsspec<2023.3.0 # fix dask failures in pytest
  - dask>=0.19.0
  - pip
  - setuptools
  - setuptools_scm
  - setuptools_scm_git_archive
  - pip:
    - pytest-runner==5.1
    - pytest==5.1.2
    - tiledb
  - zipp<3.16
