name: tiledbvcf-py
channels:
  - conda-forge
dependencies:
  - python>=3.4
  - pybind11=2.3.0
  - pyarrow>=0.16.0
  - dask>=0.19.0
  - pip
  - pip:
    - setuptools==39.0.1
    - pytest-runner==5.1
    - pytest==5.1.2
