name: tiledbvcf-py
channels:
  - conda-forge
dependencies:
  - python>=3.4
  - pybind11=2.3.0
  - pyarrow==3.0.0
  - dask>=0.19.0
  - pip
  - setuptools
  - setuptools_scm
  - setuptools_scm_git_archive
  - pip:
    - pytest-runner==5.1
    - pytest==5.1.2
    - tiledb
