name: tiledbvcf-py
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - pybind11>=2.11.1
  - pyarrow>=11.0.0
  - fsspec<2023.3.0 # fix dask failures in pytest
  - dask>=0.19.0
  - pip
  - setuptools
  - setuptools_scm
  - setuptools_scm_git_archive
  - pip:
    - pytest-runner>=6.0.0
    - pytest>=7.4.0
    - tiledb
  - zipp<3.16
