name: tiledbvcf-py
channels:
  - conda-forge
dependencies:
  - numpy<2
  - python<3.12 # based on available tiledb-py wheels
  - pybind11
  - pyarrow>=14.0.2 # for pyarrow security fix
  - fsspec
  - dask
  - pip
  - setuptools
  - setuptools_scm
  - setuptools_scm_git_archive
  - pip:
    - pytest
    - pytest-runner
