name: tiledbvcf-py
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - pybind11=2.3.0
  - pyarrow==14.0.1
  - fsspec<2023.3.0 # fix dask failures in pytest
  - dask>=0.19.0
  - pip
  - setuptools
  - setuptools_scm
  - setuptools_scm_git_archive
  - tiledb-py
  - pip:
    - pytest-runner==5.1
    - pytest==5.1.2
    - tiledb
  - zipp<3.16
