name: Build Variants

on:
  push:

jobs:
  # This job should mimic conda-feedstock build
  libtiledbvcf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Mamba environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: ci
          create-args: -c bioconda tiledb spdlog fmt cli11 htslib catch2=2.13.8
          init-shell: >-
            bash
      - name: Configure CMake
        shell: micromamba-shell {0}
        run: |
          cmake -S libtiledbvcf -B build \
            -D CMAKE_BUILD_TYPE=Release \
            -D BUILD_SHARED_LIBS=ON \
            -D CMAKE_INSTALL_PREFIX=install \
            -D TILEDBVCF_ENABLE_TESTS=OFF \
            -D TILEDBVCF_FORCE_EXTERNAL_DEPENDENCIES=ON \
            -D CMAKE_PREFIX_PATH=$CONDA_PREFIX
      - name: Build using CMake
        shell: micromamba-shell {0}
        run: |
          cmake --build build --config Release
      - name: Install using CMake
        shell: micromamba-shell {0}
        run: |
          cmake --install build --config Release

      - name: Upload install folder
        uses: actions/upload-artifact@v4
        with:
          name: libtiledbvcf
          path: install/*

      # Tests
      # - name: Run unit tests 
      #   shell: micromamba-shell {0}
      #   run: |
      #     ctest --test-dir build
      # - name: Run CLI tests
      #   run: |
      #     libtiledbvcf/test/run-cli-tests.sh build libtiledbvcf/test/inputs


  # This job should mimic conda-feedstock build
  python-bindings-external-libtiledbvcf:
    needs: libtiledbvcf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Mamba environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: ci
          create-args: tiledb python=3.11 pip pytest
          init-shell: >-
            bash
      - name: Download libtiledbvcf artifact
        uses: actions/download-artifact@v4
        with:
          name: libtiledbvcf
          path: install
      - name: Build Python bindings 
        shell: micromamba-shell {0}
        env:
          tiledbvcf_DIR: "${{ github.workspace }}/install"
        run: |
          pip install -v --no-deps . --config-settings=cmake.define.TILEDBVCF_ONLY_PYTHON_BINDINGS=ON 

      - name: Run tests
        run: |
          pytest apis/python


  # This job should mimic wheel build
  python-bindings-wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install build dependencies
        run: |
          sudo apt-get install -y ninja-build bcftools
      - name: Build and install using PiP
        run: |
          pip install -v .[test]

      - name: Run tests
        run: |
          pytest apis/python

