name: Nightly
# High-level notes:
# * Installs libtiledb and libtiledbvcf into ./install/
# * Manually updates library path so that tiledbvcf-py can link to
#   the shared objects in ./install/
on:
  push:
    paths:
      - '.github/workflows/nightly.yml'
      - 'ci/nightly/**'
  pull_request:
    paths:
      - '.github/workflows/nightly.yml'
      - 'ci/nightly/**'
  schedule:
    - cron: "0 3 * * *" # Every night at 3 AM UTC (10 PM EST; 11 PM EDT)
  workflow_dispatch:
jobs:
  nightly:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-libtiledb-${{ matrix.branches.libtiledb }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, ubuntu-latest]
        branches:
          - {libtiledb: release-2.26, tiledb-py: 0.32.0}
          - {libtiledb: dev, tiledb-py: dev}
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.15
    steps:
      - name: Clone TileDB
        uses: actions/checkout@v4
        with:
          repository: TileDB-Inc/TileDB
          ref: ${{ matrix.branches.libtiledb }}
          path: TileDB
      - name: Clone TileDB-Py
        uses: actions/checkout@v4
        with:
          repository: TileDB-Inc/TileDB-Py
          ref: ${{ matrix.branches.tiledb-py }}
          path: TileDB-Py
      - name: Clone TileDB-VCF
        uses: actions/checkout@v4
        with:
          path: TileDB-VCF
          fetch-depth: 0 # fetch everything for python setuptools_scm
      - name: Build libtiledb
        run: bash TileDB-VCF/ci/nightly/build-libtiledb.sh
      - name: Setup to build htslib from source (macOS)
        if: runner.os == 'macOS'
        run: brew install autoconf automake
      - name: Build libtiledbvcf
        run: bash TileDB-VCF/ci/nightly/build-libtiledbvcf.sh
      - name: Confirm linking (Linux)
        if: runner.os == 'Linux'
        run: |
          ldd install/lib/libtiledb.so
          ldd install/lib/libtiledbvcf.so
      - name: Confirm linking (macOS)
        if: runner.os == 'macOS'
        run: |
          otool -L install/lib/libtiledb.dylib
          otool -L install/lib/libtiledbvcf.dylib
      - name: Install bcftools (for tests) (Linux)
        if: runner.os == 'Linux'
        run: sudo apt install bcftools
      - name: Install bcftools (for tests) (macOS)
        if: runner.os == 'macOS'
        run: brew install bcftools
      - name: Test libtiledbvcf
        run: bash TileDB-VCF/ci/nightly/test-libtiledbvcf.sh
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Build tiledb-py from source
        run: bash TileDB-VCF/ci/nightly/build-tiledb-py.sh
      - name: Build (and test) tiledbvcf-py
        run: bash TileDB-VCF/ci/nightly/build-tiledbvcf-py.sh
  issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    needs: nightly
    if: ( failure() || cancelled() ) && github.repository_owner == 'TileDB-Inc' && github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@v4
      - name: Open Issue
        uses: TileDB-Inc/github-actions/open-issue@main
        with:
          name: nightly build
          label: nightly-failure
          assignee: awenocur,gspowley,ihnorton,Shelnutt2,jdblischak
        env:
          TZ: "America/New_York"
