name: Nightly build against nightly libtiledb
# High-level notes:
# * Installs libtiledb and libtiledbvcf into ./install/
# * Manually updates library path so that tiledbvcf-py can link to
#   the shared objects in ./install/
# * conda is only used to install Python dependencies
on:
  push:
    paths:
      - '.github/workflows/nightly.yml'
      - 'ci/nightly/**'
  pull_request:
    paths:
      - '.github/workflows/nightly.yml'
      - 'ci/nightly/**'
  schedule:
    - cron: "0 3 * * *" # Every night at 3 AM UTC (10 PM EST; 11 PM EDT)
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-libtiledb-${{ matrix.libtiledb_version }}
    strategy:
      fail-fast: false
      matrix:
        libtiledb_version: [release-2.17, dev]
        os: [macos-11, ubuntu-latest]
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.15
    steps:
      - name: Clone TileDB
        uses: actions/checkout@v3
        with:
          repository: TileDB-Inc/TileDB
          ref: ${{ matrix.libtiledb_version }}
          path: TileDB
      - name: Clone TileDB-VCF
        uses: actions/checkout@v3
        with:
          path: TileDB-VCF
          fetch-depth: 0 # fetch everything for python setuptools_scm
      - name: Build libtiledb
        run: bash TileDB-VCF/ci/nightly/build-libtiledb.sh
      - name: Setup macOS (to build htslib from source)
        if: runner.os == 'macOS'
        run: brew install autoconf automake
      - name: Build libtiledbvcf
        run: bash TileDB-VCF/ci/nightly/build-libtiledbvcf.sh
      - name: Confirm linking (linux)
        if: runner.os == 'Linux'
        run: |
          ldd install/lib/libtiledb.so
          ldd install/lib/libtiledbvcf.so | grep tile
      - name: Confirm linking (osx)
        if: runner.os == 'macOS'
        run: |
          otool -L install/lib/libtiledb.dylib
          otool -L install/lib/libtiledbvcf.dylib | grep tile
      - name: Install bcftools (for tests) (linux)
        if: runner.os == 'Linux'
        run: sudo apt install bcftools
      - name: Install bcftools (for tests) (osx)
        if: runner.os == 'macOS'
        run: brew install bcftools
      - name: Test libtiledbvcf
        run: bash TileDB-VCF/ci/nightly/test-libtiledbvcf.sh
      - name: Setup conda env
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: TileDB-VCF/ci/nightly/environment.yaml
          cache-environment: true
      - name: Build (and test) tiledbvcf-py
        # need -l to activate conda env
        shell: bash -l {0}
        run: bash TileDB-VCF/ci/nightly/build-tiledbvcf-py.sh
  issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    needs: build
    if: ( failure() || cancelled() ) && github.repository_owner == 'TileDB-Inc' && github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@v3
      - name: Open Issue
        uses: TileDB-Inc/github-actions/open-issue@main
        with:
          name: nightly build
          label: nightly-failure
          assignee: awenocur,gspowley,ihnorton,Shelnutt2
        env:
          TZ: "America/New_York"
