# Cloned from https://github.com/TileDB-Inc/tiledb-quarto-template

name: Render and deploy Quarto files
on: 
  push:
  pull_request:

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: "Install Quarto"
      uses: quarto-dev/quarto-actions/setup@v2
      
    - name: "Quarto render"
      shell: bash
      run: |
        pip install quartodoc "pydantic<2" griffe==0.32.3
        # create a symlink to the tiledbvcf python package, so it doesn't have to be installed
        ln -s apis/python/src/tiledbvcf
        quartodoc build
        quarto render --fail-if-warnings
        # https://github.com/quarto-dev/quarto-cli/issues/493

    - name: "Deploy to gh-pages"
      uses: peaceiris/actions-gh-pages@v3
      # Change to the name of your repo's primary branch name:
      if: github.ref == 'refs/heads/main' && github.repository_owner == 'TileDB-Inc'
      with:
        # This is GitHub Actions magic; no secrets for us to manage; and this works first-time
        # without any extra configs other than visiting Settings -> Pages in your GitHub repo.
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs
        destination_dir: docs
