name: Build Python client for Windows
on:
  push:
    paths:
      - '.github/workflows/windows.yml'
      - 'apis/python/**'
      - 'ci/*.bat'
      - 'ci/gha-win-env.yml'
      - 'libtiledbvcf/**'
  pull_request:
    paths:
      - '.github/workflows/windows.yml'
      - 'apis/python/**'
      - 'ci/*.bat'
      - 'ci/gha-win-env.yml'
      - 'libtiledbvcf/**'
  workflow_dispatch:
defaults:
  run:
    shell: cmd /C CALL {0}
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Install conda env
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ci/gha-win-env.yml
          cache-environment: true
          init-shell: cmd.exe
          condarc: |
            channels:
              - conda-forge
              - tiledb
            channel_priority: strict
      - name: Build libtiledbvcf
        run: cmd /C CALL ci\build-libtiledbvcf.bat
      - name: libtiledbvcf version
        run: tiledbvcf.exe version
      - name: Build tiledbvcf-py
        run: cmd /C CALL ci\build-tiledbvcf-py.bat
      - name: tiledbvcf-py version
        run: python -c "import tiledbvcf; print(tiledbvcf.version)"
      - name: Test
        run: pytest apis\python\tests
